"""unique constraint on user and unique id

Revision ID: 6fff0793cd17
Revises: b149175aeb2b
Create Date: 2024-03-06 19:28:40.949939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fff0793cd17'
down_revision: Union[str, None] = 'b149175aeb2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('files_remote_id_key', 'files', type_='unique')
    op.drop_constraint('files_unique_id_key', 'files', type_='unique')
    op.create_unique_constraint('_user_file_id_uc', 'files', ['user_id', 'unique_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_file_id_uc', 'files', type_='unique')
    op.create_unique_constraint('files_unique_id_key', 'files', ['unique_id'])
    op.create_unique_constraint('files_remote_id_key', 'files', ['remote_id'])
    # ### end Alembic commands ###
