"""add mime type

Revision ID: 7383c62bf48f
Revises: 086f55fe8c2d
Create Date: 2024-01-19 01:22:40.453531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7383c62bf48f'
down_revision: Union[str, None] = '086f55fe8c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('mime_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'mime_type')
    # ### end Alembic commands ###
