"""add category favorite column

Revision ID: aaddf08b3d7b
Revises: 2afe5a50d6d4
Create Date: 2023-12-17 05:25:45.819542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaddf08b3d7b'
down_revision: Union[str, None] = '2afe5a50d6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_favorite')
    # ### end Alembic commands ###
