"""add sub file type

Revision ID: e0a06b1f2cdb
Revises: 086f55fe8c2d
Create Date: 2024-01-14 03:50:34.728653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0a06b1f2cdb'
down_revision: Union[str, None] = '086f55fe8c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

sub_file_category = sa.Enum('doc_text', 'doc_image', 'doc_video', 'doc_audio', name='subfilecategory')


def upgrade() -> None:
    sub_file_category.create(op.get_bind())
    op.add_column(
        'files',
        sa.Column('sub_type', sub_file_category, nullable=True),
    )

    op.execute("""ALTER TYPE filetype rename to filecategory""")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""ALTER TYPE filecategory rename to filetype""")

    op.drop_column('files', 'sub_type')
    sub_file_category.drop(op.get_bind())
